name: Build test

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TIME_FILE: ./BuildTime/BuildTimeProvider-Build.cs
  CURRENT_TIME_STRING: what

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./BuildTime/
      
    - name: Build console
      run: dotnet build ./BuildTime/BuildTime.csproj --no-restore

    - name: "Build time file (Windows)"
      if: matrix.os == 'windows-latest'
      run: |
        echo "CURRENT_TIME_STRING=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $env:GITHUB_ENV
        echo "public static partial class BuildTimeProvider" >> $env:BUILD_TIME_FILE
        echo "{" >> $env:BUILD_TIME_FILE
        echo "    static partial void Initialize()" >> $env:BUILD_TIME_FILE
        echo "    {" >> $env:BUILD_TIME_FILE
        echo "        BuildTimeString  = ""${{ env.CURRENT_TIME_STRING }}"";" >> $env:BUILD_TIME_FILE
        echo "    }" >> $env:BUILD_TIME_FILE
        echo "}" >> $env:BUILD_TIME_FILE

    - name: "Print build time file (Windows)"
      if: matrix.os == 'windows-latest'
      run: |
        cat $env:BUILD_TIME_FILE

    - name: "Build time file (Linux)"
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "CURRENT_TIME_STRING=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
        echo "public static partial class BuildTimeProvider" >> $BUILD_TIME_FILE
        echo "{" >> $BUILD_TIME_FILE
        echo "    static partial void Initialize()" >> $BUILD_TIME_FILE
        echo "    {" >> $BUILD_TIME_FILE
        echo "        BuildTimeString  = \"$CURRENT_TIME_STRING\";" >> $BUILD_TIME_FILE
        echo "    }" >> $BUILD_TIME_FILE
        echo "}" >> $BUILD_TIME_FILE

    - name: "Print build time file (Linux)"
      if: matrix.os == 'ubuntu-latest'
      run: |
        cat $BUILD_TIME_FILE

    - name: Run application
      run: dotnet run --project ./BuildTime/BuildTime.csproj
